#!/usr/bin/env php
<?php
require_once 'vendor/autoload.php';
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Helper\HelperSet;
use Doctrine\DBAL\Tools\Console\Helper\ConnectionHelper;
use Symfony\Component\Console\Helper\DialogHelper;
use Doctrine\ORM\Tools\Console\ConsoleRunner;
use DI\ContainerBuilder;

use DoctrineMigrationsHelper\CommandSet;

$builder = new ContainerBuilder();
$builder->useAnnotations(false);
$builder->addDefinitions(__DIR__."/config/config.php");
$container = $builder->build();

$console = new Application("Bolt Extensions Console", "1.0");


/***** Load in Database ORM & Migrations Commands *******/
$helperSet = ConsoleRunner::createHelperSet($container->get("Doctrine\ORM\EntityManager"));
$helperSet->set(new DialogHelper);
$console->setHelperSet($helperSet);
ConsoleRunner::addCommands($console);

$migrations_set = new CommandSet($container->get("Doctrine\DBAL\Driver\Connection"));
$migrations_set->configuration = $container->get("migrations");
$console->addCommands($migrations_set->getCommands());
/***** End Migrations Commands *******/


/***** Add the local console commands *****/
$console->addCommands($container->get('console.commands'));


$console->run();